spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_management_system
    username: root
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082


jwt:
  secret:
    key: 5P4ku0lDX1M7cLTDTbawb9vD55tsxkeZ6WmmkRljfW6TiXoFBG0iF0j0sfWoyYgR

token:
  expiration: 86400000

eureka:
  instance:
    appname: AUTH-SERVICE
  client:
    register-with-eureka: true
    fetch-registry: true
