spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_management_system
    username: root
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: AUTH-SERVICE

server:
  port: 8082


jwt:
  secret:
    key: 5P4ku0lDX1M7cLTDTbawb9vD55tsxkeZ6WmmkRljfW6TiXoFBG0iF0j0sfWoyYgR

token:
  expiration: 86400000

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka
