spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_management_system
    username: root
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

eureka:
  instance:
    ip-address: true
    appname: BLOG-SERVICE
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

