eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE:8082
          predicates:
            - Path=/user/**

        - id: BLOG-SERVICE
          uri: lb://BLOG-SERVICE:8081
          predicates:
            - Path=/blog/**
          filters:
            - AuthenticationFilter

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE:8083
          predicates:
            - Path=/rating/**
          filters:
            - AuthenticationFilter

  application:
    name: GATEWAY-SERVICE

jwt:
  secret:
    key: 5P4ku0lDX1M7cLTDTbawb9vD55tsxkeZ6WmmkRljfW6TiXoFBG0iF0j0sfWoyYgR